[workspace]
resolver = "3"
members = ["vix-core", "vix-wire", "vixen-primitives", "vixen-runtime"]

[workspace.package]
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vixenware/vixen"
homepage = "https://github.com/vixenware/vixen"

[workspace.dependencies]
blake3 = { version = "1", default-features = false }
facet = { git = "https://github.com/facet-rs/facet", rev = "5705fa6c51289bea49f5729c52dc5e23cedce4f8" }
facet-format = { git = "https://github.com/facet-rs/facet", rev = "5705fa6c51289bea49f5729c52dc5e23cedce4f8" }
facet-json = { git = "https://github.com/facet-rs/facet", rev = "5705fa6c51289bea49f5729c52dc5e23cedce4f8" }
facet-reflect = { git = "https://github.com/facet-rs/facet", rev = "5705fa6c51289bea49f5729c52dc5e23cedce4f8" }
facet-toml = { git = "https://github.com/facet-rs/facet", rev = "5705fa6c51289bea49f5729c52dc5e23cedce4f8" }
facet-value = { git = "https://github.com/facet-rs/facet", rev = "5705fa6c51289bea49f5729c52dc5e23cedce4f8", default-features = false }
hex = "0.4"
libc = "0.2.180"
object = "0.39"
phon = { git = "https://github.com/bearcove/phon-next", rev = "be6e6de5132c9eed3277e9345923117482028b65" }
sha2 = "0.10"
snark = { git = "https://github.com/bearcove/snark", rev = "e85ba57226f239a1407f496051af7e0c80855d57" }
snark-dsl = { git = "https://github.com/bearcove/snark", rev = "e85ba57226f239a1407f496051af7e0c80855d57" }
taxon = { git = "https://github.com/bearcove/weavy", rev = "743a7abe8f999ab4122df1cc02e2441849210a23" }
tempfile = "3.23"
tracing = { version = "0.1.43", default-features = false, features = ["std", "attributes"] }
weavy = { git = "https://github.com/bearcove/weavy", rev = "743a7abe8f999ab4122df1cc02e2441849210a23" }
windows-sys = "0.61"

[patch.crates-io]
copypatch = { git = "https://github.com/bearcove/weavy", rev = "743a7abe8f999ab4122df1cc02e2441849210a23" }
taxon = { git = "https://github.com/bearcove/weavy", rev = "743a7abe8f999ab4122df1cc02e2441849210a23" }
weavy = { git = "https://github.com/bearcove/weavy", rev = "743a7abe8f999ab4122df1cc02e2441849210a23" }

[patch."https://github.com/facet-rs/facet?rev=5705fa6c51289bea49f5729c52dc5e23cedce4f8"]
copypatch = { git = "https://github.com/bearcove/weavy", rev = "743a7abe8f999ab4122df1cc02e2441849210a23" }
taxon = { git = "https://github.com/bearcove/weavy", rev = "743a7abe8f999ab4122df1cc02e2441849210a23" }
weavy = { git = "https://github.com/bearcove/weavy", rev = "743a7abe8f999ab4122df1cc02e2441849210a23" }


[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(facet_no_doc)", "cfg(kani)"] }

[workspace.lints.clippy]
disallowed_methods = "deny"

[profile.dev.package.vix-core]
opt-level = 2

[profile.dev.package.weavy]
opt-level = 2

[profile.dev.package.blake3]
opt-level = 3
